CREATE TABLE ORDERED_CARS
(
    ID BIGINT,
    AMOUNT INT,
    QUANTITY INT,
    IDOFCAR BIGINT,
    ORDER_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID) on DELETE CASCADE

);